Release 7.7.0 Use new Google Analytics 4 script
silinternational/simplesamlphp-module-material pull request #120
Opened 2022-11-29 14:17 UTC by Baggerone

2022-11-29 15:56 UTC, forevermatt requested changes
The code changes look fine, but I think this will be a breaking change (thus `8.0.0`, not `7.7.0`) since this will break people's usage of Google Analytics unless they change what analytics ID value they are providing.

2022-11-29 16:43 UTC, Baggerone commented
> The code changes look fine, but I think this will be a breaking change (thus `8.0.0`, not `7.7.0`) since this will break people's usage of Google Analytics unless they change what analytics ID value they are providing.

Thanks. I've modified the PR title.

2022-11-29 18:20 UTC, forevermatt approved these changes

2022-11-30 00:33 UTC, Schparky approved these changes

2022-11-30 00:44 UTC, Schparky approved these changes

2022-11-30 00:49 UTC, Schparky commented
> > The code changes look fine, but I think this will be a breaking change (thus `8.0.0`, not `7.7.0`) since this will break people's usage of Google Analytics unless they change what analytics ID value they are providing.
> 
> Thanks. I've modified the PR title.

Just for discussion and for greater clarity, what would happen if someone updated to this version and did NOT change their ID. Would it break anything other than analytics? If not, I think one could argue that it's not a breaking change if analytics is an "optional" or non-essential feature of the software. I realize, of course, it's really not an issue because the chances of someone outside of SIL using this software is extremely small. So the reason to use proper semantic versioning is for self-discipline and good practice, which has its own value. Thus the reason for the question.

2022-11-30 08:21 UTC, merged